### Send POST request with json body
POST http://localhost:3000/api/registration
Content-Type: application/json

{
  "id": 999,
  "value": "content"
}
##################################################################
### REGISTRATION
POST http://localhost:3000/api/sign-up
Content-Type: application/json

{
  "firstName": "Jordach",
  "lastName": "MAKAYA",
  "email": "jmakaya@me.com",
  "password": "Password@@2026"
}

### LOGIN
POST http://localhost:3000/api/sign-in
Content-Type: application/json

{
  "id": 999,
  "value": "content",
  "email": "jmakaya@me.com",
  "password": "Password@@2026"
}
