### Send POST request with json body
POST http://localhost:3001/api/auth/sign-up
Content-Type: application/json

{
  "id": 999,
  "value": "content"
}
##################################################################
### REGISTRATION
# @no-cookie-jar
POST http://localhost:3001/api/auth/sign-up
Content-Type: application/json

{
  "firstName": "Thaliane",
  "lastName": "MAKAYA",
  "email": "thali121e@me.com",
  "password": "Password@@2026"
}

### LOGIN
POST http://localhost:3001/api/auth/sign-in
Content-Type: application/json

{
  "email": "jmakaya@me.com",
  "password": "Password@@2026"
}
